# Generated by Django 5.2.3 on 2025-06-20 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_start_date', models.DateField(verbose_name='Дата желаемого посещения')),
                ('payment_method', models.CharField(choices=[('1', 'Наличные'), ('2', 'Перевод')], max_length=255, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('1', 'Новая'), ('2', 'Идет обучение'), ('3', 'Обучение завершено')], max_length=1, verbose_name='Статус')),
                ('cousre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.coursemodel', verbose_name='Название курса')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
